version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      docker: 18
  pre_build:
    commands:
      - echo Pre-build started on `date`
      - echo Installing node packages...
      - npm install
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image... 
      - npm run build
      - docker build -t privacy-choices:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag privacy-choices:$CODEBUILD_RESOLVED_SOURCE_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/privacy-choices:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/privacy-choices:$CODEBUILD_RESOLVED_SOURCE_VERSION