version: 2

jobs:

  # Build job
  build:
    working_directory: ~/privacy-choices

    # Build on a Node Docker image
    docker:
      - image: circleci/node:10.15.3

    # Build job steps
    steps:

      # Checkout code
      - checkout

      # Restore node_modules cache (either exact match or latest cache)
      - restore_cache:
          keys:
            - node_modules-{{ checksum "package.json" }}
            - node_modules-

      # Dependency install
      - run: npm install

      # Perform build
      - run: npm run build

      # Zip artifacts
      - run: zip -r privacy-choices.zip build

      # Store artifacts
      - store_artifacts:
          path: privacy-choices.zip

      # Cache node_modules
      - save_cache:
          paths:
            - node_modules
          key: node_modules-{{ checksum "package.json" }}